#
# 
#
# Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
#
require 'json'

# adding necessary json serialization methods to standard classes.
class Object
  def to_jaxb_json_hash
    return self
  end
  def self.from_json o
    return o
  end
end

class String
  def self.from_json o
    return o
  end
end

class Boolean
  def self.from_json o
    return o
  end
end

class Numeric
  def self.from_json o
    return o
  end
end

class Time
  #json time is represented as number of milliseconds since epoch
  def to_jaxb_json_hash
    return (to_i * 1000) + (usec / 1000)
  end
  def self.from_json o
    if o.nil?
      return nil
    else
      return Time.at(o / 1000, (o % 1000) * 1000)
    end
  end
end

class Array
  def to_jaxb_json_hash
    a = Array.new
    each { | _item | a.push _item.to_jaxb_json_hash }
    return a
  end
end

class Hash
  def to_jaxb_json_hash
    h = Hash.new
    each { | _key, _value | h[_key.to_jaxb_json_hash] = _value.to_jaxb_json_hash }
    return h
  end
end

module EnunciateHelpers
  LAMB_CLASS_AWARE = ->(_item) do
    java_clazz = _item['@class']
    clazz_array_parts = java_clazz.split('.')
    short_clazz = clazz_array_parts.pop
    clazz_package = clazz_array_parts.map do |e| e[0] = e.first.capitalize; e end.join("::")
    clazz = clazz_package + "::" + short_clazz
    Object.const_get(clazz).send(:from_json, _item)
  end
end


module Introsde

module Finalproj

module Model

  # (no documentation provided)
  class Exercises 

    # (no documentation provided)
    attr_accessor :exercise

    # the json hash for this Exercises
    def to_jaxb_json_hash
      _h = {}
      if !exercise.nil?
        _ha = Array.new
        exercise.each { | _item | _ha.push _item.to_jaxb_json_hash }
        _h['exercise'] = _ha
      end
      return _h
    end

    # the json (string form) for this Exercises
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this Exercises with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['exercise'].nil?
          _oa = _o['exercise']
            if(_oa.is_a? Hash)
              @exercise = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @exercise =  Introsde::Finalproj::Model::Exercise.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @exercise = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @exercise.push Introsde::Finalproj::Model::Exercise.from_json(_item)
                 else
                   @exercise.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @exercise = _oa
            end
          end
    end

    # constructs a Exercises from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end

module Introsde

module Finalproj

module Model

  # (no documentation provided)
  class Exercise 

    # (no documentation provided)
    attr_accessor :exerciseName
    # (no documentation provided)
    attr_accessor :caloriesPerHour

    # the json hash for this Exercise
    def to_jaxb_json_hash
      _h = {}
      _h['exerciseName'] = exerciseName.to_jaxb_json_hash unless exerciseName.nil?
      _h['caloriesPerHour'] = caloriesPerHour.to_jaxb_json_hash unless caloriesPerHour.nil?
      return _h
    end

    # the json (string form) for this Exercise
    def to_json
      to_jaxb_json_hash.to_json
    end

    #initializes this Exercise with a json hash
    def init_jaxb_json_hash(_o)
        if !_o['exerciseName'].nil?
          _oa = _o['exerciseName']
            if(_oa.is_a? Hash)
              @exerciseName = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @exerciseName =  String.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @exerciseName = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @exerciseName.push String.from_json(_item)
                 else
                   @exerciseName.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @exerciseName = _oa
            end
          end
        if !_o['caloriesPerHour'].nil?
          _oa = _o['caloriesPerHour']
            if(_oa.is_a? Hash)
              @caloriesPerHour = EnunciateHelpers::LAMB_CLASS_AWARE.call(_oa) if _oa['@class']
              @caloriesPerHour =  Float.from_json(_oa) unless _oa['@class']
            elsif (_oa.is_a? Array)
              #an array(of hashes hopefully) or scalar
              @caloriesPerHour = Array.new
              _oa.each { | _item | 
                 if ((_item.nil? || _item['@class'].nil?)rescue true)
                   @caloriesPerHour.push Float.from_json(_item)
                 else
                   @caloriesPerHour.push EnunciateHelpers::LAMB_CLASS_AWARE.call(_item)
                 end
               }
            else
                @caloriesPerHour = _oa
            end
          end
    end

    # constructs a Exercise from a (parsed) JSON hash
    def self.from_json(o)
      if o.nil?
        return nil
      else
        inst = new
        inst.init_jaxb_json_hash o
        return inst
      end
    end
  end

end

end

end
